name: wf-cd
on:
  push:
    branches:
      - production
jobs:
  build-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Building the website using Parcel #for building the website
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-develop"
  deploy-artifact-develop:
    needs: "build-upload-artifact"
    runs-on: "ubuntu-latest"
    environment:
      name: "production-env"
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Artifacts on Github pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-develop"
          token: ${{github.token}}

